coverage:
  status:
    project:
      # Auto-adjust required overall coverage
      default:
        target: auto
    patch:
      # Required coverage for new code
      default:
        target: 75%
