# Forked PR Solution 3: require a "safe to test" label, set by the maintainer.
name: Solution 3

on:
  pull_request_target:
    types: [labeled]

jobs:

  # Run forked repo PR in base repo context, but only if labelled
  test:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe')
    steps:

      # Checkout the forked repo PR code into the base repo
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Passes, with forked PR code analyzed in privileged context, after review
      - name: Privileged processing
        run: echo "Some sensitive command that executes code (tests) and/or uses secrets"
