name: Merge to Main

on:
  push:
    branches:
      - main

jobs:

  coverage:
    name: Baseline coverage report
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install testing dependencies
      run: pip install pytest pytest-cov

    - name: Run tests
      run: pytest --cov-config=.coveragerc --cov=hello_pp

    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true

  sast:
    name: Security/SAST
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        auditOn: push
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        publishDeployment: 415
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
