name: Codecov Flow

on: [pull_request]

jobs:
  test:
    name: Test and Cover
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install testing dependencies
      run: pip install pytest pytest-cov

    - name: Run tests
      run: pytest --cov-config=.coveragerc --cov=hello_pp

    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
