name: Pull Request

on: [pull_request]

jobs:

  lint:
    # Stability issues with this action. Pinned beta version.
    # https://github.com/psf/black/issues/2079
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@20.8b1
        with:
          args: ". --check"

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install testing dependencies
      run: pip install pytest pytest-cov

    - name: Run tests
      run: pytest --cov-config=.coveragerc --cov=hello_pp

    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true

  sast:
    name: SAST Scan
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: Semgrep Python ruleset
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/python

      - name: Semgrep Bandit ruleset
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/bandit
