# .github/workflows/release-force-bump-minor.yaml
#
# Force a minor level version bump and create a new release.
#
# - Environments restrict branches and people that can release.
# - Updates and commits the changelog.
# - Tags the commit with the new release.
# - Builds and uploads the package to PyPI.

name: Release Force Bump Minor

# Manual execution.
on: workflow_dispatch

jobs:
  release:
    name: Release Minor Version to PyPI Test
    environment:
      name: Test PyPI Release
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Python Semantic Release
      run: pip install python-semantic-release==v7.15.3

    - name: Bump minor version and release
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "action@github.com"
        semantic-release publish --minor
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
