# .github/workflows/release.yaml
#
# Create a new release.
#
# - Environments restrict branches and people that can release.
# - Updates and commits the changelog.
# - Tags the commit with the new release.
# - Builds and uploads the package to PyPI.
#
# Manual triggers will completely stop if a tag already exists.

name: Release

# Manual execution.
on: workflow_dispatch

# Automatic execution.
# on:
#   push:
#     branches:
#       - main

jobs:
  release:
    name: Release to PyPI Test
    environment:
      name: Test PyPI Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Python Semantic Release
      uses: relekang/python-semantic-release@v7.15.3
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
        github_token: ${{ secrets.GH_TOKEN }}
