# .github/workflows/semantic-release.yaml
#
# - Updates and commits the changelog.
# - Tags the commit with the new release.
# - Builds and uploads the package to PyPI.
#
# Running multiple times without changes will
# cause it to fail. Manual triggers will completely
# stop if a tag already exists.

name: Release

# Automatic execution.
# on:
#   push:
#     branches:
#       - main

# Manual execution.
on: workflow_dispatch

jobs:
  release:
    name: Release to PyPI Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # github_token: ${{ secrets.GH_TOKEN }}
