name: security

on: [pull_request]

# Manual execution.
# on: workflow_dispatch

jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        auditOn: push
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        publishDeployment: 415
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Dump env
      env:
        FOO: ${{ secrets.SEMGREP_APP_TOKEN }}
      run: echo "FOO [$FOO]"
