name: security/semgrep

on: [pull_request]

# on:
#   push:
#     # Run SAST scanning on all branches except main.
#     branches:
#     - '*'
#     - '!main'

# Manual execution.
# on: workflow_dispatch

jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        auditOn: push
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        publishDeployment: 415
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
