on:
  pull_request: {}
  push:
    # Run SAST scanning on all branches except main.
    branches:
    - '*'
    - '!main'

# Manual execution.
# on: workflow_dispatch

name: security/semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        auditOn: push
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        publishDeployment: 415
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
