name: test

# on: [pull_request]

on:
  pull_request_target:
    branches:
      - main
  # push:
  #   branches:
  #     - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install testing dependencies
      run: pip install pytest pytest-cov

    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageCommand: pytest
        coverageLocations: |
          ${{github.workspace}}/coverage.xml:coverage.py
        debug: true
